import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import List from '@editorjs/list';
import ImageTool from "@editorjs/image";
import RawTool from '@editorjs/raw';
import LinkTool from '@editorjs/link';
import Paragraph from '@editorjs/paragraph';
import CodeTool from '@editorjs/code';
import Embed from '@editorjs/embed';
import AttachesTool from '@editorjs/attaches';
import Table from '@editorjs/table';
import Quote from '@editorjs/quote';
import Underline from '@editorjs/underline';
import Delimiter from '@editorjs/delimiter';
import InlineCode from '@editorjs/inline-code';
import TextVariantTune from '@editorjs/text-variant-tune';
import Marker from '@editorjs/marker';

window.Header = Header;
window.List = List;
window.RawTool = RawTool;
window.EditorJS = EditorJS;
window.ImageTool = ImageTool;
window.LinkTool = LinkTool;
window.Paragraph = Paragraph;
window.CodeTool = CodeTool;
window.Embed = Embed;
window.AttachesTool = AttachesTool;
window.Table = Table;
window.Quote = Quote;
window.Underline = Underline;
window.Delimiter = Delimiter;
window.InlineCode = InlineCode;
window.TextVariantTune = TextVariantTune;
window.Marker = Marker;